### PR TITLE
Redesign AdminPanel to Bootstrap4

### PR DESCRIPTION
**Pull request by dsimko**
Online preview is here: http://46.183.65.66:8080/brixdemo/admin

I know that new design is not nicer than original but big advantage is that creators of new plugins can use Bootstrap for their UI.

### CODE REVIEW

**Comment by kbachl** [comment]
Hello Dan,

quite nice work. The buttons are sometimes a bit too near to text and it somehow seems broken on my iPhone (initial load - menu is not showing as expected; IOS 9).

Can you make sure all existing brix plugins got the redesign? I would like to merge it as a whole and not have forgotten something.

I'll try to do some dev' work this week, but had an accident last week thats why I didnt respond to you yet.

**Comment by dsimko** [comment]
Hello Korbinian,
thank you. Do you mean all plugins from https://github.com/brix-cms/brix-cms-plugins? I have already started to rewriting some of these plugins but it will probably take some time to make it usable. 
I hope that it wasn't something too serious.

**Comment by kbachl** [comment]
I didnt mean the brix-cms-plugins but all plugins that are in the git main repository. Its important to have changes like those at least on a comprehensive level over the whole brix-cms repo.

**Comment by martin-g** [comment]
Hi,

I also think it is a good thing to use some CSS framework everywhere in the application.
Just make sure it is possible to override the default CSS with a custom theme, in case someone need it.

**Comment by kbachl** [comment]
> CSS framework everywhere

No, not everywhere  - only in the backend!

The content-side frontend has to be clear. - I think you meant it that way but I just to make sure we all agree on that.

**Comment by martin-g** [comment]
> The content-side frontend has to be clear. - I think you meant it that way but I just wanted to make sure we all agree on that.

Correct!

**Comment by dsimko** [comment]
Agreed. 
With regard to plugins I think it is done. There is definitely a lot of space for improvements but I would say that all basic plugins are displaying quite well. 
Good point Martin, I didn't have in mind the possibility to support custom themes. But we can improve this sometimes later when we will have some feedback.

**Comment by martin-g** [comment]
This is not an advertisement by any means!
Just check the theme switcher at http://wb-mgrigorov.rhcloud.com/
One can provide its own theme as well.

**Comment by dsimko** [comment]
Thanks Martin, I like it! But it isn't so important for now. I have created an issue (https://github.com/brix-cms/brix-cms/issues/181) in order to not forget on it.

**Comment by kbachl** [comment]
I think having this as an issue is ok so we can concentrate more on getting brix 8 ready asap. I would merge this request if its ok to you martin; 

When merging this we can advance faster and then maybe cut a brix 8.0.0-beta out of it and have this #181 reserved for brix 8.0.0.final ?

(I would go that way as Dan expressed his need to get a fast, workable version and he seems to like to have it "official" in some way)

**Comment by martin-g** [comment]
You are the driving force here!
Feel free to merge PRs as soon as you are happy with the changes! Don't wait for me!
I'll try to do code reviews and share my opinion when I have something to say.

**Comment by kbachl** [comment]
@martin-g I know - but since I'm not up to date 100% yet its not my intention to push too much too fast :)

**Pull request merged**
